id: I6224FCD7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:08:12+00:00'
last_modified: '2022-06-09T07:38:43.905145+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25389
  title: རི་མོར་བལྟས་ནས་གྲངས་ཀ་ངོས་འཛིན་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CEAE:
      image_group_id: I1KG25391
      title: Volume 1 of ri mor bltas nas grangs ka ngos 'dzin pa/
      total_pages: 65
      order: 1
      base_file: CEAE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
