id: P007930
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25389
  title: རི་མོར་བལྟས་ནས་གྲངས་ཀ་ངོས་འཛིན་པ།
  author: ''
  volumes:
    183a5745e16c482393742321b5df026e:
      image_group_id: I1KG25391
      title: Volume 1 of ri mor bltas nas grangs ka ngos 'dzin pa/
      volume_number: 1
      total_pages: 65
      base_file: v001.txt
