id: P007930
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25389
  title: རི་མོར་བལྟས་ནས་གྲངས་ཀ་ངོས་འཛིན་པ།
  author: ''
  volumes:
    1e4de9211957463685295613599fb2cf:
      image_group_id: I1KG25391
      title: ''
      volume_number: 1
      total_pages: 65
ebook_metadata:
  title: རི་མོར་བལྟས་ནས་གྲངས་ཀ་ངོས་འཛིན་པ།
  author: ''
  sku: P007930
  cover: cover.jpg
  layers:
  - pagination
